"""Authoritative public exports for shared contracts."""

from .analysis import EmailAnalysis, TimelineEvent
from .correlation import (
    CorrelationIndicatorType,
    CorrelationStrength,
    RelatedCase,
    RelatedCasesResponse,
    SharedIndicator,
)
from .ai_investigator import (
    AIAskRequest,
    AIInvestigationAction,
    AIInvestigationRequest,
    AIInvestigatorResponse,
    AIInvestigatorStatus,
)
from .auth import (
    Permission,
    UpdateProfileRequest,
    UpdateRoleRequest,
    UserListResponse,
    UserProfile,
    UserRole,
)
from .api import (
    AnalyzeCaseResponse,
    CaseListResponse,
    CaseSummary,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
)
from .detection import DetectionFinding, DetectionResult
from .email import (
    AttachmentEvidence,
    AuthenticationResults,
    ContractModel,
    ExtractedIOC,
    MailboxAddress,
    MimePart,
    ParsedEmail,
    ReceivedHop,
)
from .enums import (
    AnalysisStatus,
    AuthenticationVerdict,
    DetectionCategory,
    EnrichmentStatus,
    GeoLocationStatus,
    IOCSource,
    IOCType,
    ReputationVerdict,
    RiskLevel,
    Severity,
    TimelineEventType,
)
from .risk import RiskReason, RiskResult
from .threat_intel import GeoLocationResult, ThreatFinding, ThreatIntelResult
from .threat_workspace import (
    IntelligenceStatus,
    ProviderStatusRecord,
    ProviderWorkspaceStatus,
    ThreatCaseReference,
    ThreatIntelligenceWorkspace,
    ThreatIOCRecord,
    ThreatSummary,
)
from .workflow import (
    AnalystNote,
    AnalystNoteListResponse,
    AuditAction,
    AuditEvent,
    AuditEventListResponse,
    CreateAnalystNoteRequest,
    CreateWatchlistRequest,
    UpdateAnalystNoteRequest,
    WatchlistEntry,
    WatchlistResponse,
)

__all__ = [
    "AIAskRequest",
    "AIInvestigationAction",
    "AIInvestigationRequest",
    "AIInvestigatorResponse",
    "AIInvestigatorStatus",
    "AnalystNote",
    "AnalystNoteListResponse",
    "AnalysisStatus",
    "AnalyzeCaseResponse",
    "AttachmentEvidence",
    "AuditAction",
    "AuditEvent",
    "AuditEventListResponse",
    "AuthenticationResults",
    "AuthenticationVerdict",
    "CaseListResponse",
    "CaseSummary",
    "CorrelationIndicatorType",
    "CorrelationStrength",
    "ContractModel",
    "CreateAnalystNoteRequest",
    "CreateWatchlistRequest",
    "DetectionCategory",
    "DetectionFinding",
    "DetectionResult",
    "EmailAnalysis",
    "EnrichmentStatus",
    "ErrorDetail",
    "ErrorResponse",
    "ExtractedIOC",
    "GeoLocationResult",
    "GeoLocationStatus",
    "HealthResponse",
    "IOCSource",
    "IOCType",
    "IntelligenceStatus",
    "MailboxAddress",
    "MimePart",
    "ParsedEmail",
    "Permission",
    "ProviderStatusRecord",
    "ProviderWorkspaceStatus",
    "ReceivedHop",
    "ReputationVerdict",
    "RelatedCase",
    "RelatedCasesResponse",
    "RiskLevel",
    "RiskReason",
    "RiskResult",
    "Severity",
    "SharedIndicator",
    "ThreatFinding",
    "ThreatCaseReference",
    "ThreatIntelligenceWorkspace",
    "ThreatIOCRecord",
    "ThreatIntelResult",
    "ThreatSummary",
    "TimelineEvent",
    "TimelineEventType",
    "UpdateAnalystNoteRequest",
    "UpdateProfileRequest",
    "UpdateRoleRequest",
    "UserListResponse",
    "UserProfile",
    "UserRole",
    "WatchlistEntry",
    "WatchlistResponse",
]
