/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemStatusRouteImport } from './routes/system-status'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system-status',
  path: '/system-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases': typeof CasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/dashboard': typeof DashboardRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/system-status': typeof SystemStatusRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/cases/': typeof CasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/system-status'
    | '/threat-intelligence'
    | '/cases/$caseId'
    | '/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/system-status'
    | '/threat-intelligence'
    | '/cases/$caseId'
    | '/cases'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/dashboard'
    | '/reports'
    | '/settings'
    | '/system-status'
    | '/threat-intelligence'
    | '/cases/$caseId'
    | '/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  DashboardRoute: typeof DashboardRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SystemStatusRoute: typeof SystemStatusRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  CasesIndexRoute: typeof CasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-status': {
      id: '/system-status'
      path: '/system-status'
      fullPath: '/system-status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  DashboardRoute: DashboardRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SystemStatusRoute: SystemStatusRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  CasesIndexRoute: CasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
